@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Система «Стандарт»

Person(admin, "Администратор", "Администратор ИТ-систем банка")
Person(call_center_employee, "Сотрудник call-центра", "Оператор call-центра")
Person(back_office_manager, "Менеджер бэк-офиса", "Сотрудник бэк-офиса банка")
Person(client, "Клиент", "Клиент банка")

System(int, "Интернет-банк", "ASP.NET MVC 4.5, .NET Framework 4.5")
System(abs, "АБС", "АБС")
System(cc, "Система управления call-центром", "Система управления call-центром")
System_Ext(pcc, "Партнерский call-центр", "Партнерский call-центр")
System(sms, "СМС-шлюз", "СМС-шлюз")
System_Ext(telecom, "Телеком-оператор", "Телеком-оператор")
System(site, "Сайт", "PHP и React.js")

' client
Rel(client, site, "Запросы", "HTTP/HTTPS")
Rel(client, pcc, "Обращается за поддержкой", "Телефония")

' admin
Rel(admin, int, "Запросы", "HTTPS")
Rel(admin, abs, "Администрирует систему", "")
Rel(admin, cc, "Администрирует call-центр", "HTTPS")
Rel(admin, site, "Запросы", "HTTP/HTTPS")

' call_center_employee
Rel(call_center_employee, cc, "Обслуживает клиентов", "HTTPS")

' back_office_manager
Rel(back_office_manager, abs, "Работает с бухгалтерией и операциями", "")
Rel(back_office_manager, site, "Работает с операциями", "")

' systems

Rel(site, int, "Запросы", "HTTP/HTTPS")

Rel(cc, sms, "Запросы", "")
Rel(sms, telecom, "Запросы", "")

@enduml
